// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwn4MinCRas2X0nS42BotjTbpPhnt6wzs',
    appId: '1:269415581954:web:e6d9d019b430d9ad131a1b',
    messagingSenderId: '269415581954',
    projectId: 'cloneproject-55fbf',
    authDomain: 'cloneproject-55fbf.firebaseapp.com',
    storageBucket: 'cloneproject-55fbf.firebasestorage.app',
    measurementId: 'G-519TSXLNZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxRq7Cs6nZWyu7wePHiQzHgQ63vrZDwoE',
    appId: '1:269415581954:android:cdfa5642a286b206131a1b',
    messagingSenderId: '269415581954',
    projectId: 'cloneproject-55fbf',
    storageBucket: 'cloneproject-55fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawf9jbgIPR6nRTw4w58ENKQsHz_gfUKY',
    appId: '1:269415581954:ios:f121f7da91c4e16f131a1b',
    messagingSenderId: '269415581954',
    projectId: 'cloneproject-55fbf',
    storageBucket: 'cloneproject-55fbf.firebasestorage.app',
    androidClientId: '269415581954-ms6f6v362lt8f3dich7k2tmtpkndc96l.apps.googleusercontent.com',
    iosClientId: '269415581954-1s962a0kcg75516io0lme7h7jhodi8lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCawf9jbgIPR6nRTw4w58ENKQsHz_gfUKY',
    appId: '1:269415581954:ios:f121f7da91c4e16f131a1b',
    messagingSenderId: '269415581954',
    projectId: 'cloneproject-55fbf',
    storageBucket: 'cloneproject-55fbf.firebasestorage.app',
    androidClientId: '269415581954-ms6f6v362lt8f3dich7k2tmtpkndc96l.apps.googleusercontent.com',
    iosClientId: '269415581954-1s962a0kcg75516io0lme7h7jhodi8lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwn4MinCRas2X0nS42BotjTbpPhnt6wzs',
    appId: '1:269415581954:web:d4c77d73dfefa0de131a1b',
    messagingSenderId: '269415581954',
    projectId: 'cloneproject-55fbf',
    authDomain: 'cloneproject-55fbf.firebaseapp.com',
    storageBucket: 'cloneproject-55fbf.firebasestorage.app',
    measurementId: 'G-YVGKG42GGM',
  );

}